# github healthfile config
blank_issues_enabled: false
contact_links:
  - name: Manifold Finance & OpenMEV Forums and Support
    url: https://forums.manifoldfinance.com
    about: Please ask and answer questions here.
  - name: Manifold Finance/OpenMEV Security & Bug Bounties
    url: https://github.com/manifoldfinance/security
    about: Please report security vulnerabilities here.
